# Serveur
server.port=8080

spring.application.name=capnex-backend
spring.datasource.url=jdbc:postgresql://localhost:5433/capnex
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT
jwt.secret=capnex-secret-key-2026-brvm-uemoa-trading-app
jwt.expiration=86400000

# CORS
spring.web.cors.allowed-origins=http://localhost:5173

# App
app.name=CAPNEX PRO
app.version=3.0

# Time
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
